### ISSUE TITLE
[DS105L] Test that AWS services work

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/DS105#1]
This issue will involve several of us. Check completed tasks once you've finished them.

**Util links:**

- [Last year's scripts](https://github.com/LSE-DSI/lse-ds105-course-notes/tree/develop/weeks/week03/last%20year)

**Tasks**

- [x] @Mayazure: set up EC2 instance for DS105L. This instance should be kept on until ~Week 07. (**deadline:** Tue 24/01 but ideal Mon 23/01)
- [x] @Mayazure: set up Docker -- we're still doing Docker for this, right?. (**deadline:** Tue 24/01 but ideal Mon 23/01)
- [x] @jonjoncardoso: provide a list of student IDs (**deadline:** Tue 24/01 but ideal Mon 23/01)
- [x] @Mayazure:  create student home folders (**deadline:** Tue 24/01 but ideal Mon 23/01)
- [x] @jonjoncardoso: check access to EC2 as a student (`test` user) (**deadline:** Tue 24/01)
- [x] @mc-o: test access to the cloud, rehearse for W03 class. (**deadline:** Thu 26/01 but ideal Wed 25/01)

**Comment by Mayazure** [comment]
Yes we are still using docker. I'll try to setup the cloudformation script on Monday, but in case I don't have enough time, I'll do it using our traditional approach (manually setup ;) ).

**Comment by jonjoncardoso** [comment]
Everything works, from my end. @mc-o let us know once you have tested, too.

**Comment by mc-o** [comment]
I can access the system using both users. Everything looks fine

**Comment by jonjoncardoso** [comment]
Thanks everyone. Now that this is done, I'm focused on #3
